spring:
  profiles.active: cloud
server:
  port: ${PORT:0}
security:
  basic:
    enabled: false

---
spring:
  profiles: cloud # For deployment in Cloud Foundry
  cloud:
    services:
      registrationMethod: route
producer:
  ribbon:
    ServerListRefreshInterval: 5000
ribbon:
  IsSecure: true
