server:
  port: ${PORT:0}

management:
  endpoints:
    web:
      base-path: /manage

endpoints:
  env:
    keys-to-sanitize: pwd,uid,password,secret,key,client_id,client_key # suffix or regex

logging:
  level:
    com.netflix: INFO
    org.springframework.cloud: INFO
    io.pivotal.sfdc: INFO

info:
  component: Auth Service
  build:
    name: ${project.name:authService}
    description: ${project.description:oauth2 service to login to SFDC}
    version: ${project.version:0.0.1-SNAPSHOT}
    group: ${project.groupId:io.pivotal.sfdc}
    artifact: ${project.artifactId:authService}

sfdc:
  client_id: '{cipher}bf926ee3ed7e60ce8e0920ae8b45011b91eb2737d3c2fe95796ab2fa2afd7b69536a903ddb07ec54b78a5bdf6bc85dbaf8604639926bdbf32e5c755bff18b1c1eabe9ec4b8de5d3463a4384c666a7ce8f212bcf25fe535e40c9e6063044e751c35935e4cf129da1b713c5814ae3e9215'
  client_key: '{cipher}dcdeca12ec0600f7638e3d4b8ad5f70a0a890425e21c2cb6d43fc40f8ae67fe52316d991c71fcf87d77aa698e5d93cee'
  uid: '{cipher}4064c897a0c62edf29d91163469ea7fcb2a1ad318b8f91632a16028830869cda3dae8bd5fdb17763b4c6056b6c4e96cf'
  pwd: '{cipher}79fd64cf398391f214f12554d2da41f9ffb0c74dbac514d850e763dbcbb1e0f7286ad3cdd7205e3425c2d03350d6669a537481a12c0e3930da28b45ac852550d'

---
spring:
  profiles: local
  instance:
    nonSecurePort: ${server.port}
  redis:
    host: redis
    port: 6379
eureka:
  instance:
    preferIpAddress: true
    hostname: authservice
    nonSecurePort: ${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:discovery}:8761/eureka/
# Ribbon Configurations
producer:
  ribbon:
    ServerListRefreshInterval: 5000
ribbon:
  IsSecure: false

---
spring:
  profiles: cloud # For deployment in Cloud Foundry
  cloud:
    services:
      registrationMethod: direct
producer:
  ribbon:
    ServerListRefreshInterval: 5000
ribbon:
  IsSecure: false

sfdc:
  client_id: 3MVG9A2kN3Bn17hv8siDyJtftcr88aXG3TpBJIqO8QZac_dpXPEoQy08vgi651aB8y6QdfgCkW0HsDIyQeH1V
  client_key: 4631320832041516337
  uid: jigsheth@sfdc.com
  pwd: Pivotal1234mpY9LIqi4zImvqRZI8zYP2p3
