server:
  port: ${PORT:0}

spring:
  sleuth.sampler.percentage: 1.0
  zipkin.sender.type: rabbit

management:
  cloudfoundry:
    skip-ssl-validation: true
    enabled: true
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: '*'
  endpoint:
    health:
      roles: USER
      show-details: always
    env:
      keys-to-sanitize:  pwd,uid,password,secret,key,client_id,client_key # suffix or regex

logging:
  level:
    com.netflix: INFO
    org.springframework.cloud: INFO
    io.pivotal.sfdc: DEBUG
---
spring:
  profiles: local
  # instance:
  #   nonSecurePort: ${server.port}
  redis:
    host: redis
    port: 6379
eureka:
  instance:
    preferIpAddress: true
    hostname: authservice
    # nonSecurePort: ${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:discovery}:8761/eureka/
# Ribbon Configurations
producer:
  ribbon:
    ServerListRefreshInterval: 5000
ribbon:
  IsSecure: false
sfdc:
  client_id: '{cipher}AgCLCcOKz1eJyFD0BMiBDkugesclHnuDZLQZh9qsElHYqOpUjVVW0k2K9tMzjbnvAe2VhpYYqMx/U4UbWGTdNs6CQckKMmh93sQAir65fiqJpgnhHBP7Kk27MtLG5nHvOtv0UXDiltOVuKkfepXTxuxwVwYbSehzcCQbDFRRKnuTGwHkeCK/2snHSyt0mADKNmMxYquCpQzuUSXMRyQ8tFd1qaJaM4sraN7lluax+v3kKuAXP//l7fR1Nj2LwziEiRCeB6oR613pvnMOdc0aDQnVRt5ro3F7FYgjhV2qLvSKD7ee8rVsxHUE/GA6mngYz1lEIZFyTsk1J+by9TnjsuSahK9Sredm8Xjs2JtieAjKtInHGhkarzMdu4bJrLrKfgsGiqAQ5ztwpuMez+uOWuE6iV4fqEJVILgkeKAxLnL+w/hlTLACN7eB1QEWygULWos4Nxv8+i1ks1MbnLD9wuag+Nv8Z+ZzO2aCA4vgvpl7BgixSiCBnzfFGues4Fz8eOJMIGson8EKcyNQLSesm2kTkoRAVyyEpwUWU0tJFZGb7AacIc1VMC4d10pku3QT8UFTjnGxqN+0hf0fc4EiOP9oV39zonCwtcUKc3kwFCN1qfd/VgB0NOx+CGaQef4Eok6yv2L5uUA8nAuP/NycGIqKYZC+x0rUQQ3h+qHPSAz4HJYKNwOTf+O3Z5p1ybsGxTa8YpFNurOlCq5wxmyGKREVkrKuQ0Di28K+OYnYzLUs1oeB1ILHuHeC24boTdP52bZT5M+yS0YHzM9m7qwtbFe593ezWGaEd2rxRuD55yc13+dlS+7MHstyoYlEsBW9qF8='
  client_key: '{cipher}AgBBnaHbbokaZhq0r8mz9i5XZ0uPZiXjBUTGpdpUfyIWseQs5HQzeVQ8/wpHDGwMJX724fuUxk8KBMvgPXqUYJ6gjWT5Cp6Dmy2BJnG7ispf472WoG0hWMaUwm/JACzdM1Erfwxy5ey5syyOdUwtildN6TSOValVLKYdKxPS7tegWcPZ1kiqQae1i0ycyPcl1xHQOExSJ/7eUrL9K9QtXYmf2dA2dZXx/XyffKCWrpQDgB40xWfcTh4L4L/DjfYU4rRyzTre6/J4hqJCbrjaKtnHx743LS7mJf68gu05rtPnwp3gIv5xavVQZcBwW8njA3Hn8IK0zNSLN4ygP18GI4/0hBsumikgSYIFXU46zP3b/NptQCDJH6x8AtxIuYDSVFXl9fm9LOobD43uGQ49qfKvJKdna1l9efQbP/r2uyHpJvpgQi1g7U2sF3nihXWLegIBJnCzGCqIpotK4RByA+p59r4z5vFG2B2G90SXcQvDNaFuhVN+kQOGr5wXnuP6/bLFI5JdI0RYmEW4v1l76bN8szCWmddAz4WhezaA+JWtHGS+IEIuWhHBLpewTJIFG7P7O1K9ujMJCKexgJUFKhcIcPEjtrVD0U2inMAXYfF71bzuKCjxwOusllwvK4atyJpEudHBiioWdcenmncGbmfx6XMGyi2rKfJTBcD6xGKqH9qYnQUcUFkLWJtuDHvUE8zwAK9L2JaY45RVtpry4XcXr4sOzg27PiM4qUx/tP7psQ=='
  uid: '{cipher}AgCeokmR1y1tqjv3k18NXhEt73OuL/JdoBxv5ZXI+Wt+v/L2WGF0llfBdXKzTO+iYkreKKtq7W5FTFsxE8m+jg5tsnFS/nmlhMlANTpMp6DuSWAU/QGz1gHfTdEjDFqAlEpoh82FVBGSoQnFNr3IguB5dlomOCba4zBCfTM9NI2/tLE1/2Ltr3GDuYwfOP2jBtnTXvw67Sop1zUuOQr+DvsdHRg0JdKPSlnXRf8oHIUUxFXu8U3qKr52yP2V6PsezsEuS+ssB/MuVWAnk7TSwZnyH+7QbAfX2CcO/ZfMFhBgb2U9gszc870x8TFnjFPxyCdM6OJV7kyndROg/en/FiEXaEnR5/+hb24W4KPg95gmx5GpecpCbzuYDhB6j/qD2vpJzJnxTNEJb3nSH2AALCwi4HnrMCuMZ6RpI2uLIP67hd0rUe4hdgHOcjUpnt/6pVHQIid1L6oO8r7Stn63688byMWgn1hdW2WtkdhQSrffV0p8zkEMEXENHnYIFppA0iXAF3G0w/5ts2Sg+hf91X086xgpZUkdkSMcmszO1FSfwR/2p1wMy6yF3yynJkvYiy+dbrkJIWnoDH/8zzKf+SWgr3FVkBOB/FbynvRos5XLC1tYWWnjR0b5zzdv8bZ3p+6NqwoP9jloC0/z+RCHJ8PK3CWgWlgFbdhMEyo/dvpxyp2qhVyb9Y1QisxqeFHiz0Q5h4beH6e+pS2Lr5NlN4oOblaIn6Duyi5LsyeHmT842Q=='
  pwd: '{cipher}AgBJOtpWzMiFJB6u3MuM7rVTGWBm9y+TQ5T6uchfr0sXjg6yxsTWNQACVvONQT+bOJUGTRfxcF7Uj1eR9uSjl4wRT5EIf8CrLjmP/zfERib/jHMDp7UP2ok+9aISY7HhDyAmiixK+onKDXvPoyTCDgMv7lHwhp6kOwU8hOVudI9WC0FoRtfzZ46PzxnxGnAFa635tH5YSlNPXglj6DgMFAspi0IpaIcrZTiVjWyQehxioZQTUmQfJdz8k5ibgbnT4AfsC/y8o+Np+eknnTX7jo/b4QDPKAH87MAUR2nP+GvxXdvI3UAaWdCUg4+iqyB4z/Bxbz6QQJ2Sn2iNJa4fanWoWGluzysS/kBKgRv3TUmaWzamO+042ZuqU9tzBmCuNVvvjkq1XGossLVxJIStGBlONbQC9jKmKJSwNwxexg6yNCJDHrMiLbYd5ALts+hrcfYCH4m3j70TiAz6/qb9GhgROJ2JqdkIrhfW0tGCV9NEn0Zps3gacMcPOGtyWUXTNP+CXsOadnUGjrGqK477Yi0VlOR7lraXGA760a2RHsVjPiaD+s5lDd3c7Z3bDZ/9VAiXYohhv4XqF/V9S6zM5F1DnRJAFdTF7x6HW3BR8ofjDbk4FUCSYOcT0Biyc4GypmvzqDS7Lrt91duNw+xXZ1iz/d+MUDB3FcB36RL2ed5KNxoTpb8CJ3XRhlk7vXLY8riIgfFMpCjTKz59atL7kEd49kga+ptzpbPRZpHzS9BI3a3YxJCud7otMQv2M7XFOFk='
---
spring:
  profiles: cloud # For deployment in Cloud Foundry
  cloud:
    services:
      registrationMethod: direct
  redis:
    host: ${vcap.services.cache-service.credentials.host:redis}
    port: ${vcap.services.cache-service.credentials.port:6379}
    password: ${vcap.services.cache-service.credentials.password}

producer:
  ribbon:
    ServerListRefreshInterval: 5000
ribbon:
  IsSecure: false
sfdc:
  client_id: '{cipher}5d634a83aa3afa94b3f100263037e6c032a14dd06e9433193b565fcb20c72df7179cf3788b2d2fea06bb02fa66fe16c2e8e68d8154b2519eabc56adfce28b9f6526ac6710fe6c98f3cfd4739e9f3bd4bff396c853ccc8d169a9d7ed4aac490be1fdcce9498c9b9adfce9851101c06821'
  client_key: '{cipher}0a9b68bdc73c21c48814b6848dc9c8feb3021e0d8b9bdaad286fe0ef6a9887d04647fcfccdb2f26012264b58798c4612'
  uid: '{cipher}b9894e593ccf582c2400e3f1947035aef643f9cdb6000602897f4e4463019b62c291f13818d471e0bb116a8581abbe45'
  pwd: '{cipher}1e31b869a9da8df05eaa42ae760dea8b6dcf365c104b38c8594efe233f040bc972ddbf60a253048fb09c8175068e23e421683d2494a939f8a60f5dc22bf6b392'
# sfdc:
#   client_id: 3MVG9A2kN3Bn17hv8siDyJtftcr88aXG3TpBJIqO8QZac_dpXPEoQy08vgi651aB8y6QdfgCkW0HsDIyQeH1V
#   client_key: 4631320832041516337
#   uid: jigsheth@sfdc.com
#   pwd: Pivotal1234mpY9LIqi4zImvqRZI8zYP2p3
