server:
  port: ${PORT:0}

spring:
  sleuth.sampler.percentage: 1.0
  zipkin.sender.type: rabbit

management:
  cloudfoundry:
    skip-ssl-validation: true
    enabled: true
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: '*'
  endpoint:
    health:
      roles: USER
      show-details: always
    env:
      keys-to-sanitize:  pwd,uid,password,secret,key,client_id,client_key # suffix or regex

logging:
  level:
    com.netflix: INFO
    org.springframework.cloud: INFO
    io.pivotal.sfdc: INFO

sfdc:
  client_id: '{cipher}{key:encryptkey}1698e2e9fd0d90aca654c717648e24a72f98eb6554ec0826cf14780f442e216cf78ca161ade12ae55b3cc6c499c21b316b67f6376e2af5ba0cf3a09fec301cb696359c5d140487b5b2dd5e3d099014bc19d4e8e9b0726c611c1e74b2312d57ef8f6a19d207ce04411c020594d9600e3d'
  client_key: '{cipher}{key:encryptkey}e30732f185124b828dd628da978a7fbbe0c5ad3ca0d4af20e953c102203346c2be760e06e2a07e896cedd042eebceec8'
  uid: '{cipher}{key:encryptkey}e33b101f972c9b1322be313d3cc388ce25628e88a7a873d743519aec330d70b7cb3fcc24f4b5339135f58cc2fed2e2d0'
  pwd: '{cipher}{key:encryptkey}54789554feaa341cde1890bd73b472394083a4e1d8f043394db1647292e1ad00c5c8ac4733b0552ebca51c7c5f70fcd920bd2f4447b086647ef0042923053264'

---
spring:
  profiles: local
  # instance:
  #   nonSecurePort: ${server.port}
  redis:
    host: redis
    port: 6379
eureka:
  instance:
    preferIpAddress: true
    hostname: authservice
    # nonSecurePort: ${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
#      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
      defaultZone: http://${EUREKA_HOST:discovery}:8761/eureka/
# Ribbon Configurations
producer:
  ribbon:
    ServerListRefreshInterval: 5000
ribbon:
  IsSecure: false
---
spring:
  profiles: cloud # For deployment in Cloud Foundry
  cloud:
    services:
      registrationMethod: direct
producer:
  ribbon:
    ServerListRefreshInterval: 5000
ribbon:
  IsSecure: false

# sfdc:
#   client_id: 3MVG9A2kN3Bn17hv8siDyJtftcr88aXG3TpBJIqO8QZac_dpXPEoQy08vgi651aB8y6QdfgCkW0HsDIyQeH1V
#   client_key: 4631320832041516337
#   uid: jigsheth@sfdc.com
#   pwd: Pivotal1234mpY9LIqi4zImvqRZI8zYP2p3
