spring:
  profiles.active: cloud
server:
  port: ${PORT:0}
security:
  basic:
    enabled: false

management:
  context-path: /manage
  security:
    enabled: false

endpoints:
  env:
    keys-to-sanitize: pwd,uid,password,secret,key,client_id,client_key # suffix or regex

logging:
  level:
    com.netflix: INFO
    org.springframework.cloud: INFO
    io.pivotal.sfdc: DEBUG

info:
  component: Contact Service
  app:
    name: ${project.name:contactService}
    description: ${project.description:SFDC Contact Service}
    version: ${project.version:0.0.1-SNAPSHOT}
    group: ${project.groupId:io.pivotal.sfdc}
    artifact: ${project.artifactId:contactService}

eureka:
  instance:
    #preferIpAddress: false
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health
    homePageUrlPath: /
#    registryFetchIntervalSeconds: 5
#    leaseRenewalIntervalInSeconds: 5
#  client:
#    registerWithEureka: true
#    fetchRegistry: true

sfdc:
  service:
    unavailable: '{"status":503,"data": "Service currently unavailable."}'
  authservice:
    endpoint: https://authservice

---
spring:
  profiles: local
  instance:
    nonSecurePort: ${server.port}
  redis:
    host: redis
    port: 6379
eureka:
  instance:
    preferIpAddress: true
    hostname: contactservice
    nonSecurePort: ${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
sfdc:
  authservice:
    endpoint: http://authservice

---
spring:
  profiles: cloud # For deployment in Cloud Foundry
  cloud:
    services:
      registrationMethod: route
producer:
  ribbon:
    ServerListRefreshInterval: 5000
ribbon:
  IsSecure: true
#eureka:
#  instance:
#    securePortEnabled: true
#    nonSecurePortEnabled: false
#    secureVirtualHostName: ${spring.application.name}
#    metadataMap:
#      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
#  client:
#    serviceUrl:
#      defaultZone: ${vcap.services.p-service-registry.credentials.uri}/eureka/
