spring:
  profiles.active: cloud
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: ${PORT:0}
security:
  basic:
    enabled: false
ssl:
  port: 8443
  keystore:
    file: classpath:/server.jks
    pass: ${STORE_PASS:secret}

---
spring:
  profiles: cloud # For deployment in Cloud Foundry
  cloud:
    services:
      registrationMethod: direct
producer:
  ribbon:
    ServerListRefreshInterval: 5000
ribbon:
  IsSecure: false
