spring:
  profiles.active: cloud
  sleuth.sampler.percentage: 1.0
  zipkin.sender.type: rabbit
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: ${PORT:0}
security:
  basic:
    enabled: false
# ssl:
#   port: 8443
#   keystore:
#     file: classpath:/server.jks
#     pass: ${STORE_PASS:secret}

logging.level:
  microsec.freddysbbq: DEBUG
  org.springframework:
    cloud:
      sleuth: INFO

---
spring:
  profiles: cloud # For deployment in Cloud Foundry
  cloud:
    services:
      registrationMethod: direct
eureka:
  instance:
    onSecurePortEnabled: false
    securePortEnabled: false
    securePort: 8080
producer:
  ribbon:
    ServerListRefreshInterval: 5000
ribbon:
  IsSecure: false
