server:
  port: ${PORT:0}

management:
  context-path: /manage

endpoints:
  env:
    keys-to-sanitize: pwd,uid,password,secret,key,client_id,client_key # suffix or regex

logging:
  level:
    com.netflix: INFO
    org.springframework.cloud: INFO
    io.pivotal.sfdc: INFO

info:
  component: Opportunity Service
  app:
    name: ${project.name:opportunityService}
    description: ${project.description:SFDC Opportunity Service}
    version: ${project.version:0.0.1-SNAPSHOT}
    group: ${project.groupId:io.pivotal.sfdc}
    artifact: ${project.artifactId:opportunityService}

sfdc:
  service:
    unavailable: '{"status":503,"data": "Service currently unavailable."}'
  authservice:
    endpoint: http://authservice

---
spring:
  profiles: local
  instance:
    nonSecurePort: ${server.port}
  redis:
    host: redis
    port: 6379
eureka:
  instance:
    preferIpAddress: true
    hostname: opportunityservice
    nonSecurePort: ${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:discovery}:8761/eureka/
# Ribbon Configurations
producer:
  ribbon:
    ServerListRefreshInterval: 5000
ribbon:
  IsSecure: false

security:
  basic:
    enabled: false

management:
  security:
    enabled: false

---
spring:
  profiles: cloud # For deployment in Cloud Foundry
  cloud:
    services:
      registrationMethod: direct
producer:
  ribbon:
    ServerListRefreshInterval: 5000
ribbon:
  IsSecure: false
#eureka:
#  instance:
#    securePortEnabled: true
#    nonSecurePortEnabled: false
#    secureVirtualHostName: ${spring.application.name}
#    metadataMap:
#      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
#  client:
#    serviceUrl:
#      defaultZone: ${vcap.services.p-service-registry.credentials.uri}/eureka/
